---

image: python:3.7-slim-stretch

stages:
  - build
  - test
  - deploy

variables:
  package: gitlab-job-guard

before_script:
  - env | sort | egrep -i 'CI|GIT'
  - pwd; pwd -P
  - python -m pip install --upgrade pip virtualenv
  - virtualenv -p python venv
  - . venv/bin/activate
  - python -m pip install --upgrade pip setuptools virtualenv wheel
  - echo '.' > requirements.txt
  - pip install -e ./
  - pip freeze -l --exclude-editable > requirements.txt
  - awk -F"'" '
      /version/ { $0=$1"'"'"$CI_COMMIT_REF_NAME"'"'"$3 }{ print $0 }
    ' setup.py > setup.py.tmp; mv -v setup.py.tmp setup.py
  - chmod +x ./setup.py
  - python ./setup.py sdist bdist_wheel
  - pip install dist/gitlab-job-guard*.tar.gz

'build-package':
  stage: build
  script:
    - echo "Built $package@$CI_COMMIT_REF_NAME ... "
  except:
    - tags

'test-python2':
  stage: test
  image: python:2.7-slim-stretch
  script:
    - python ./setup.py sdist bdist_wheel
    - pip install dist/gitlab-job-guard*.tar.gz
    - python2 $(which guard.py)
      -c='feature/' -s 'failed'
      -u 'https://gitlab.local/api/v4' -t 'dummy-api-key'
      -p 123123 -i 54982176 -w 20 -w 10; [ $? = 11 ]

'test-python3':
  stage: test
  image: python:3.7-slim-stretch
  script:
    - python3 $(which guard.py)
      -c='feature/' -s 'failed'
      -u 'https://gitlab.local/api/v4' -t 'dummy-api-key'
      -p 123123 -i 54982176 -w 20 -w 10; [ $? = 11 ]

'deploy-package':
  stage: deploy
  environment:
    name: gitlab-job-guard-package
    url:  $af_repo_url
  script:
    - echo "Deploying package to artifactory"
    - echo "Deploying $package@$CI_COMMIT_REF_NAME to $af_repo_url as $af_username ..."
    - python -m pip install --upgrade twine
    - cat setup.py
    - twine upload
        --repository-url "$af_url"
        --username       "$af_user"
        --password       "$af_password"
        dist/*
  only:
    - tags

